"""init schema

Revision ID: 6976ba126a06
Revises: 
Create Date: 2026-06-27 21:51:07.270067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6976ba126a06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('payer', sa.String(length=120), nullable=False),
    sa.Column('npi', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verified_by', sa.String(length=120), nullable=False),
    sa.Column('verified_at', sa.String(length=40), nullable=False),
    sa.Column('network', sa.String(length=120), nullable=True),
    sa.Column('plan', sa.String(length=120), nullable=True),
    sa.Column('tin', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overrides_tenant_id'), 'overrides', ['tenant_id'], unique=False)
    op.create_table('payers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('benefit_type', sa.String(length=60), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('stedi_payer_id', sa.String(length=40), nullable=True),
    sa.Column('enrollment_status', sa.String(length=30), nullable=False),
    sa.Column('network_indicator_supported', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payers_key'), 'payers', ['key'], unique=False)
    op.create_index(op.f('ix_payers_tenant_id'), 'payers', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('eligibility_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('payer_key', sa.String(length=120), nullable=False),
    sa.Column('member_id_hash', sa.String(length=64), nullable=True),
    sa.Column('member_id_enc', sa.String(), nullable=True),
    sa.Column('dob_enc', sa.String(), nullable=True),
    sa.Column('name_enc', sa.String(), nullable=True),
    sa.Column('npi', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_audit', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_checks_action'), 'eligibility_checks', ['action'], unique=False)
    op.create_index(op.f('ix_eligibility_checks_created_at'), 'eligibility_checks', ['created_at'], unique=False)
    op.create_index(op.f('ix_eligibility_checks_member_id_hash'), 'eligibility_checks', ['member_id_hash'], unique=False)
    op.create_index(op.f('ix_eligibility_checks_tenant_id'), 'eligibility_checks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # Hand-written security hardening: RLS, isolation policies, app-role grants,
    # and the SECURITY DEFINER pre-tenant login lookup. Runs AFTER table
    # creation so the GRANTs can name the tables created above.
    _post(op)


def _post(op):
    # Case-insensitive uniqueness of usernames (login lookup uses lower()).
    op.create_index("uq_users_username_lower", "users", [sa.text("lower(username)")], unique=True)

    # Enable AND force RLS so even the table owner is subject to policies.
    for t in ("users", "payers", "eligibility_checks", "overrides"):
        op.execute(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {t} FORCE ROW LEVEL SECURITY")

    # Strict tenant isolation: rows are visible only when they match the
    # session-local app.tenant_id GUC.
    for t in ("users", "eligibility_checks", "overrides"):
        op.execute(f"CREATE POLICY {t}_isolation ON {t} USING "
                   f"(tenant_id = current_setting('app.tenant_id', true)::uuid)")

    # Payers may be global (tenant_id IS NULL) or tenant-scoped.
    op.execute("CREATE POLICY payers_isolation ON payers USING "
               "(tenant_id IS NULL OR tenant_id = current_setting('app.tenant_id', true)::uuid)")

    # Least privilege for the app role: full DML only on the tenant-isolated
    # (RLS-protected) tables; read-only on the non-RLS tenant registry (tenant
    # creation is owner/seed-only); and no access at all to migration state.
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON users, payers, eligibility_checks, overrides TO preauth_app")
    op.execute("GRANT SELECT ON tenants TO preauth_app")
    op.execute("REVOKE ALL ON alembic_version FROM preauth_app")  # belt-and-suspenders: app never touches migration state

    # The ONLY RLS-exempt surface: a SECURITY DEFINER lookup used for the
    # pre-tenant login step (before app.tenant_id is known).
    op.execute("""
        CREATE OR REPLACE FUNCTION auth_lookup_user(p_username text)
        RETURNS TABLE(id uuid, tenant_id uuid, password_hash text, role text,
                      token_version int, must_change_password boolean,
                      failed_logins int, locked_until timestamptz)
        LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
            SELECT id, tenant_id, password_hash, role, token_version,
                   must_change_password, failed_logins, locked_until
            FROM users WHERE lower(username) = lower(p_username) LIMIT 1;
        $$;
    """)
    op.execute("REVOKE ALL ON FUNCTION auth_lookup_user(text) FROM PUBLIC")
    op.execute("GRANT EXECUTE ON FUNCTION auth_lookup_user(text) TO preauth_app")


def downgrade() -> None:
    # Drop the SECURITY DEFINER function first; the isolation policies are
    # dropped implicitly when their tables are dropped below.
    op.execute("DROP FUNCTION IF EXISTS auth_lookup_user(text)")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eligibility_checks_tenant_id'), table_name='eligibility_checks')
    op.drop_index(op.f('ix_eligibility_checks_member_id_hash'), table_name='eligibility_checks')
    op.drop_index(op.f('ix_eligibility_checks_created_at'), table_name='eligibility_checks')
    op.drop_index(op.f('ix_eligibility_checks_action'), table_name='eligibility_checks')
    op.drop_table('eligibility_checks')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_payers_tenant_id'), table_name='payers')
    op.drop_index(op.f('ix_payers_key'), table_name='payers')
    op.drop_table('payers')
    op.drop_index(op.f('ix_overrides_tenant_id'), table_name='overrides')
    op.drop_table('overrides')
    op.drop_table('tenants')
    # ### end Alembic commands ###
