"""Re-derive every roster payer's eligibility-check status from Stedi, and print an audit.

The payer picker's badge was a guess baked into `roster_seed.py`, and on 2026-08-03 it was wrong on
163 of 306 rows — "needs enrollment" on payers whose eligibility checks Stedi fully supports, Cigna
among them. Stedi publishes the answer per payer, so nothing here needs guessing:

    GET /2024-04-01/payers  ->  items[].transactionSupport.eligibilityCheck
                                SUPPORTED | ENROLLMENT_REQUIRED | NOT_SUPPORTED

The trap this exists to prevent: a payer's `enrollment` block may carry a real requirement for a
DIFFERENT transaction. Cigna needs enrollment for `claimPayment` and not at all for an eligibility
check — reading the presence of an enrollment block as "needs enrollment" is what produced the false
badge on a third of the roster. Only `transactionSupport.eligibilityCheck` answers this question.

Usage
-----
    python -m scripts.refresh_enrollment_status            # audit only, writes nothing
    python -m scripts.refresh_enrollment_status --emit     # print a migration-ready dict

This never writes to the database. Roster changes land as an additive, idempotent Alembic migration
(see `0041_enrollment_status_truth`) so a fresh install and an existing one agree — and so a
migration never depends on a live API key or on the network.
"""

from __future__ import annotations

import argparse
import collections
import os
import sys

import httpx

PAYERS_URL = os.environ.get("STEDI_PAYERS_URL", "https://healthcare.us.stedi.com/2024-04-01/payers")

#: Stedi's own vocabulary -> the value stored on `payers.enrollment_status`. `not_supported` is a
#: distinct fact from `needs_enrollment`: enrolling would not help, Stedi cannot run the check at all.
STATUS = {
    "SUPPORTED": "supported",
    "ENROLLMENT_REQUIRED": "needs_enrollment",
    "NOT_SUPPORTED": "not_supported",
}


def fetch_payers(api_key: str) -> dict[str, dict]:
    """Every Stedi payer, indexed by primary id AND by every alias.

    Aliases matter: the roster carries ids like `G00621` and `SKCO0` that are aliases rather than
    primary ids, and indexing on `primaryPayerId` alone silently drops them into "no Stedi match".
    """
    r = httpx.get(PAYERS_URL, headers={"Authorization": api_key}, timeout=180)
    r.raise_for_status()
    out: dict[str, dict] = {}
    for it in (r.json() or {}).get("items") or []:
        for k in {it.get("primaryPayerId"), *(it.get("aliases") or [])}:
            if k:
                out.setdefault(str(k).strip(), it)
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--emit", action="store_true", help="print a migration-ready STATUS_BY_PAYER_ID dict")
    args = ap.parse_args(argv)

    api_key = os.environ.get("STEDI_API_KEY")
    if not api_key:
        print("STEDI_API_KEY is not set (it lives in .env — load it before running).", file=sys.stderr)
        return 2

    from network_probe.payers.search import load_roster_rows

    by_pid = fetch_payers(api_key)
    rows = load_roster_rows()

    resolved: dict[str, str] = {}
    tally: collections.Counter = collections.Counter()
    changed: list[tuple[str, str, str, str]] = []
    unmatched: list[tuple[str, str]] = []

    for r in rows:
        pid = (r.get("stedi_payer_id") or "").strip()
        ours = r.get("enrollment_status")
        if not pid:
            tally[(ours, "(no payer id)")] += 1
            continue
        it = by_pid.get(pid)
        if it is None:
            tally[(ours, "(no stedi match)")] += 1
            unmatched.append((pid, r["label"]))
            continue
        truth = (it.get("transactionSupport") or {}).get("eligibilityCheck")
        tally[(ours, truth)] += 1
        mapped = STATUS.get(truth)
        if mapped:
            resolved[pid] = mapped
            if mapped != ours:
                changed.append((r["label"], r.get("state") or "", pid, f"{ours} -> {mapped}"))

    print(f"roster rows: {len(rows)}   stedi payers: {len(by_pid)}\n")
    print(f"{'our status':18} {'stedi eligibilityCheck':24} rows")
    for (ours, truth), n in sorted(tally.items(), key=lambda p: -p[1]):
        print(f"  {str(ours):16} {str(truth):24} {n}")

    print(f"\nrows whose badge would change: {len(changed)}")
    for label, state, pid, delta in changed[:40]:
        print(f"  {label[:42]:42} {state[:16]:16} {pid:8} {delta}")
    if len(changed) > 40:
        print(f"  ... and {len(changed) - 40} more")
    if unmatched:
        print(f"\nno Stedi match, left untouched: {unmatched}")

    if args.emit:
        print("\n# Regenerated by scripts/refresh_enrollment_status.py — paste into a new migration.")
        print("STATUS_BY_PAYER_ID = {")
        for pid in sorted(resolved):
            print(f'    "{pid}": "{resolved[pid]}",')
        print("}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
